In [68]:
import pandas as pd
import sklearn

In [125]:
example_corpus= {"fruitness":"I went to buy Orange and Apple apple from the grocery store",
    "computer": "I want an Apple mobile",
    "animal": "I want a cat","exam":" I want to appear for cat"}

In [82]:
cv = sklearn.feature_extraction.text.CountVectorizer(stop_words='english')

In [126]:
array = cv.fit_transform(list(example_corpus.values())).toarray()

In [128]:
array

array([[0, 2, 1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]])

In [129]:
cv.get_feature_names()

[u'appear',
 u'apple',
 u'buy',
 u'cat',
 u'grocery',
 u'mobile',
 u'orange',
 u'store',
 u'want',
 u'went']

In [130]:

print array
b = array.astype(float)
print b
import numpy as np

[[0 2 1 0 1 0 1 1 0 1]
 [0 1 0 0 0 1 0 0 1 0]
 [1 0 0 1 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 1 0]]
[[ 0.  2.  1.  0.  1.  0.  1.  1.  0.  1.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.]]


In [90]:
c = a.toarray()/b.sum(axis=1).reshape(4,1)
print c
c = c.transpose()
print c

[[ 0.          0.28571429  0.14285714  0.          0.14285714  0.
   0.14285714  0.14285714  0.          0.14285714]
 [ 0.          0.33333333  0.          0.          0.          0.33333333
   0.          0.          0.33333333  0.        ]
 [ 0.33333333  0.          0.          0.33333333  0.          0.          0.
   0.          0.33333333  0.        ]
 [ 0.          0.          0.          0.5         0.          0.          0.
   0.          0.5         0.        ]]
[[ 0.          0.          0.33333333  0.        ]
 [ 0.28571429  0.33333333  0.          0.        ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.          0.          0.33333333  0.5       ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.          0.33333333  0.          0.        ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.          0.33333333  0.33333333  0.5       ]
 [ 0.14285714  0.          0.          0.        ]]


In [91]:
data = pd.DataFrame(c,index=cv.get_feature_names(),columns=d.keys())
print data

         fruitness  computer      exam  animal
appear    0.000000  0.000000  0.333333     0.0
apple     0.285714  0.333333  0.000000     0.0
buy       0.142857  0.000000  0.000000     0.0
cat       0.000000  0.000000  0.333333     0.5
grocery   0.142857  0.000000  0.000000     0.0
mobile    0.000000  0.333333  0.000000     0.0
orange    0.142857  0.000000  0.000000     0.0
store     0.142857  0.000000  0.000000     0.0
want      0.000000  0.333333  0.333333     0.5
went      0.142857  0.000000  0.000000     0.0


In [92]:
data.transpose()

appear     apple       buy       cat   grocery    mobile  \
fruitness  0.000000  0.285714  0.142857  0.000000  0.142857  0.000000   
computer   0.000000  0.333333  0.000000  0.000000  0.000000  0.333333   
exam       0.333333  0.000000  0.000000  0.333333  0.000000  0.000000   
animal     0.000000  0.000000  0.000000  0.500000  0.000000  0.000000   

             orange     store      want      went  
fruitness  0.142857  0.142857  0.000000  0.142857  
computer   0.000000  0.000000  0.333333  0.000000  
exam       0.000000  0.000000  0.333333  0.000000  
animal     0.000000  0.000000  0.500000  0.000000

Discarded the count vectorizer approach as it doesn't take all count of all the words in all documents

In [94]:
tfidf = sklearn.feature_extraction.text.TfidfVectorizer(stop_words='english')

In [95]:
a1 = tfidf.fit_transform(list(d.values()))

In [105]:
c = a1.toarray()
print c
c = np.divide(c,c.sum(axis=1).reshape(4,1))
c

[[ 0.          0.57629822  0.36548061  0.          0.36548061  0.
   0.36548061  0.36548061  0.          0.36548061]
 [ 0.          0.55349232  0.          0.          0.          0.70203482
   0.          0.          0.44809973  0.        ]
 [ 0.70203482  0.          0.          0.55349232  0.          0.          0.
   0.          0.44809973  0.        ]
 [ 0.          0.          0.          0.77722116  0.          0.          0.
   0.          0.62922751  0.        ]]


array([[ 0.        ,  0.23975451,  0.1520491 ,  0.        ,  0.1520491 ,
         0.        ,  0.1520491 ,  0.1520491 ,  0.        ,  0.1520491 ],
       [ 0.        ,  0.32489058,  0.        ,  0.        ,  0.        ,
         0.4120825 ,  0.        ,  0.        ,  0.26302692,  0.        ],
       [ 0.4120825 ,  0.        ,  0.        ,  0.32489058,  0.        ,
         0.        ,  0.        ,  0.        ,  0.26302692,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.55261253,  0.        ,
         0.        ,  0.        ,  0.        ,  0.44738747,  0.        ]])

In [106]:
tfidf.get_feature_names()

[u'appear',
 u'apple',
 u'buy',
 u'cat',
 u'grocery',
 u'mobile',
 u'orange',
 u'store',
 u'want',
 u'went']

In [121]:
data = pd.DataFrame(c,index=d.keys(),columns=cv.get_feature_names())
print data

             appear     apple       buy       cat   grocery    mobile  \
fruitness  0.000000  0.239755  0.152049  0.000000  0.152049  0.000000   
computer   0.000000  0.324891  0.000000  0.000000  0.000000  0.412083   
exam       0.412083  0.000000  0.000000  0.324891  0.000000  0.000000   
animal     0.000000  0.000000  0.000000  0.552613  0.000000  0.000000   

             orange     store      want      went  
fruitness  0.152049  0.152049  0.000000  0.152049  
computer   0.000000  0.000000  0.263027  0.000000  
exam       0.000000  0.000000  0.263027  0.000000  
animal     0.000000  0.000000  0.447387  0.000000  


In [122]:
data.transpose()

fruitness  computer      exam    animal
appear    0.000000  0.000000  0.412083  0.000000
apple     0.239755  0.324891  0.000000  0.000000
buy       0.152049  0.000000  0.000000  0.000000
cat       0.000000  0.000000  0.324891  0.552613
grocery   0.152049  0.000000  0.000000  0.000000
mobile    0.000000  0.412083  0.000000  0.000000
orange    0.152049  0.000000  0.000000  0.000000
store     0.152049  0.000000  0.000000  0.000000
want      0.000000  0.263027  0.263027  0.447387
went      0.152049  0.000000  0.000000  0.000000

In [123]:
data['appear']

fruitness    0.000000
computer     0.000000
exam         0.412083
animal       0.000000
Name: appear, dtype: float64

In [124]:
data.to_dict()

{u'appear': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.41208250080998421,
  'fruitness': 0.0},
 u'apple': {'animal': 0.0,
  'computer': 0.32489057687003392,
  'exam': 0.0,
  'fruitness': 0.23975451048392163},
 u'buy': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'cat': {'animal': 0.55261253035951696,
  'computer': 0.0,
  'exam': 0.32489057687003392,
  'fruitness': 0.0},
 u'grocery': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'mobile': {'animal': 0.0,
  'computer': 0.41208250080998421,
  'exam': 0.0,
  'fruitness': 0.0},
 u'orange': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'store': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'want': {'animal': 0.44738746964048304,
  'computer': 0.26302692231998198,
  'exam': 0.26302692231998198,
  'fruitness': 0.0},
 u'went': {'animal': 0.0,
  'computer': 0.0,
  'exam':

TODO: 1. For a given test set (word,sentence,document) get the ranking of concepts
      2. Find similarity between two words, sentence and document (using cosine product)