In [68]:
import pandas as pd
import sklearn

In [2]:
example_corpus= {"fruitness":"I went to buy Orange and Apple apple from the grocery store",
    "computer": "I want an Apple mobile",
    "animal": "I want a cat","exam":" I want to appear for cat"}

In [82]:
cv = sklearn.feature_extraction.text.CountVectorizer(stop_words='english')

In [126]:
array = cv.fit_transform(list(example_corpus.values())).toarray()

In [128]:
array

array([[0, 2, 1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]])

In [129]:
cv.get_feature_names()

[u'appear',
 u'apple',
 u'buy',
 u'cat',
 u'grocery',
 u'mobile',
 u'orange',
 u'store',
 u'want',
 u'went']

In [130]:

print array
b = array.astype(float)
print b
import numpy as np

[[0 2 1 0 1 0 1 1 0 1]
 [0 1 0 0 0 1 0 0 1 0]
 [1 0 0 1 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 1 0]]
[[ 0.  2.  1.  0.  1.  0.  1.  1.  0.  1.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.]]


In [90]:
c = a.toarray()/b.sum(axis=1).reshape(4,1)
print c
c = c.transpose()
print c

[[ 0.          0.28571429  0.14285714  0.          0.14285714  0.
   0.14285714  0.14285714  0.          0.14285714]
 [ 0.          0.33333333  0.          0.          0.          0.33333333
   0.          0.          0.33333333  0.        ]
 [ 0.33333333  0.          0.          0.33333333  0.          0.          0.
   0.          0.33333333  0.        ]
 [ 0.          0.          0.          0.5         0.          0.          0.
   0.          0.5         0.        ]]
[[ 0.          0.          0.33333333  0.        ]
 [ 0.28571429  0.33333333  0.          0.        ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.          0.          0.33333333  0.5       ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.          0.33333333  0.          0.        ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.14285714  0.          0.          0.        ]
 [ 0.          0.33333333  0.33333333  0.5       ]
 [ 0.14285714  0.          0.          0.        ]]


In [91]:
data = pd.DataFrame(c,index=cv.get_feature_names(),columns=d.keys())
print data

         fruitness  computer      exam  animal
appear    0.000000  0.000000  0.333333     0.0
apple     0.285714  0.333333  0.000000     0.0
buy       0.142857  0.000000  0.000000     0.0
cat       0.000000  0.000000  0.333333     0.5
grocery   0.142857  0.000000  0.000000     0.0
mobile    0.000000  0.333333  0.000000     0.0
orange    0.142857  0.000000  0.000000     0.0
store     0.142857  0.000000  0.000000     0.0
want      0.000000  0.333333  0.333333     0.5
went      0.142857  0.000000  0.000000     0.0


In [92]:
data.transpose()

appear     apple       buy       cat   grocery    mobile  \
fruitness  0.000000  0.285714  0.142857  0.000000  0.142857  0.000000   
computer   0.000000  0.333333  0.000000  0.000000  0.000000  0.333333   
exam       0.333333  0.000000  0.000000  0.333333  0.000000  0.000000   
animal     0.000000  0.000000  0.000000  0.500000  0.000000  0.000000   

             orange     store      want      went  
fruitness  0.142857  0.142857  0.000000  0.142857  
computer   0.000000  0.000000  0.333333  0.000000  
exam       0.000000  0.000000  0.333333  0.000000  
animal     0.000000  0.000000  0.500000  0.000000

Discarded the count vectorizer approach as it doesn't take all count of all the words in all documents

In [94]:
tfidf = sklearn.feature_extraction.text.TfidfVectorizer(stop_words='english')

In [95]:
a1 = tfidf.fit_transform(list(d.values()))

In [105]:
c = a1.toarray()
print c
c = np.divide(c,c.sum(axis=1).reshape(4,1))
c

[[ 0.          0.57629822  0.36548061  0.          0.36548061  0.
   0.36548061  0.36548061  0.          0.36548061]
 [ 0.          0.55349232  0.          0.          0.          0.70203482
   0.          0.          0.44809973  0.        ]
 [ 0.70203482  0.          0.          0.55349232  0.          0.          0.
   0.          0.44809973  0.        ]
 [ 0.          0.          0.          0.77722116  0.          0.          0.
   0.          0.62922751  0.        ]]


array([[ 0.        ,  0.23975451,  0.1520491 ,  0.        ,  0.1520491 ,
         0.        ,  0.1520491 ,  0.1520491 ,  0.        ,  0.1520491 ],
       [ 0.        ,  0.32489058,  0.        ,  0.        ,  0.        ,
         0.4120825 ,  0.        ,  0.        ,  0.26302692,  0.        ],
       [ 0.4120825 ,  0.        ,  0.        ,  0.32489058,  0.        ,
         0.        ,  0.        ,  0.        ,  0.26302692,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.55261253,  0.        ,
         0.        ,  0.        ,  0.        ,  0.44738747,  0.        ]])

In [106]:
tfidf.get_feature_names()

[u'appear',
 u'apple',
 u'buy',
 u'cat',
 u'grocery',
 u'mobile',
 u'orange',
 u'store',
 u'want',
 u'went']

In [121]:
data = pd.DataFrame(c,index=d.keys(),columns=cv.get_feature_names())
print data

             appear     apple       buy       cat   grocery    mobile  \
fruitness  0.000000  0.239755  0.152049  0.000000  0.152049  0.000000   
computer   0.000000  0.324891  0.000000  0.000000  0.000000  0.412083   
exam       0.412083  0.000000  0.000000  0.324891  0.000000  0.000000   
animal     0.000000  0.000000  0.000000  0.552613  0.000000  0.000000   

             orange     store      want      went  
fruitness  0.152049  0.152049  0.000000  0.152049  
computer   0.000000  0.000000  0.263027  0.000000  
exam       0.000000  0.000000  0.263027  0.000000  
animal     0.000000  0.000000  0.447387  0.000000  


In [122]:
data.transpose()

fruitness  computer      exam    animal
appear    0.000000  0.000000  0.412083  0.000000
apple     0.239755  0.324891  0.000000  0.000000
buy       0.152049  0.000000  0.000000  0.000000
cat       0.000000  0.000000  0.324891  0.552613
grocery   0.152049  0.000000  0.000000  0.000000
mobile    0.000000  0.412083  0.000000  0.000000
orange    0.152049  0.000000  0.000000  0.000000
store     0.152049  0.000000  0.000000  0.000000
want      0.000000  0.263027  0.263027  0.447387
went      0.152049  0.000000  0.000000  0.000000

In [123]:
data['appear']

fruitness    0.000000
computer     0.000000
exam         0.412083
animal       0.000000
Name: appear, dtype: float64

In [124]:
data.to_dict()

{u'appear': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.41208250080998421,
  'fruitness': 0.0},
 u'apple': {'animal': 0.0,
  'computer': 0.32489057687003392,
  'exam': 0.0,
  'fruitness': 0.23975451048392163},
 u'buy': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'cat': {'animal': 0.55261253035951696,
  'computer': 0.0,
  'exam': 0.32489057687003392,
  'fruitness': 0.0},
 u'grocery': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'mobile': {'animal': 0.0,
  'computer': 0.41208250080998421,
  'exam': 0.0,
  'fruitness': 0.0},
 u'orange': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'store': {'animal': 0.0,
  'computer': 0.0,
  'exam': 0.0,
  'fruitness': 0.15204909790321566},
 u'want': {'animal': 0.44738746964048304,
  'computer': 0.26302692231998198,
  'exam': 0.26302692231998198,
  'fruitness': 0.0},
 u'went': {'animal': 0.0,
  'computer': 0.0,
  'exam':

In [25]:
from gensim.models import tfidfmodel

TODO: 1. For a given test set (word,sentence,document) get the ranking of concepts
      2. Find similarity between two words, sentence and document (using cosine product)

In [1]:
from gensim import *
tweets=[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human','human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey','frequency']] 


dictionary = corpora.Dictionary(tweets)
dictionary.save('/tmp/tweets.dict') 

raw_corpus = [dictionary.doc2bow(t) for t in tweets]

corpora.MmCorpus.serialize('/tmp/tweets.mm', raw_corpus) # store to disk

dictionary = corpora.Dictionary.load('/tmp/tweets.dict')

corpus = corpora.MmCorpus('/tmp/tweets.mm')

# Transform Text with TF-IDF
tfidf = models.TfidfModel(corpus)


corpus_tfidf = tfidf[corpus]
print corpus_tfidf

In [2]:
print corpus

MmCorpus(9 documents, 13 features, 29 non-zero entries)


In [3]:
[dictionary.get(id) for doc in corpus_tfidf for id, value in doc]

[u'interface',
 u'computer',
 u'human',
 u'computer',
 u'response',
 u'time',
 u'survey',
 u'system',
 u'user',
 u'interface',
 u'system',
 u'user',
 u'eps',
 u'human',
 u'system',
 u'eps',
 u'response',
 u'time',
 u'user',
 u'trees',
 u'trees',
 u'graph',
 u'trees',
 u'graph',
 u'minors',
 u'survey',
 u'graph',
 u'minors',
 u'frequency']

In [4]:
corpus_tfidf.obj.idfs

{0: 2.1699250014423126,
 1: 2.1699250014423126,
 2: 2.1699250014423126,
 3: 2.1699250014423126,
 4: 2.1699250014423126,
 5: 2.1699250014423126,
 6: 1.5849625007211563,
 7: 1.5849625007211563,
 8: 2.1699250014423126,
 9: 1.5849625007211563,
 10: 1.5849625007211563,
 11: 2.1699250014423126,
 12: 3.1699250014423126}

In [5]:
corpus_tfidf.obj.dfs


{0: 2,
 1: 2,
 2: 2,
 3: 2,
 4: 2,
 5: 2,
 6: 3,
 7: 3,
 8: 2,
 9: 3,
 10: 3,
 11: 2,
 12: 1}

In [6]:
array=[]
for i in range(len(corpus_tfidf.corpus)):
    array.append(corpus_tfidf.corpus[i])

In [7]:
array

[[(0, 1.0), (1, 1.0), (2, 1.0)],
 [(1, 1.0), (3, 1.0), (4, 1.0), (5, 1.0), (6, 1.0), (7, 1.0)],
 [(0, 1.0), (6, 1.0), (7, 1.0), (8, 1.0)],
 [(2, 2.0), (6, 2.0), (8, 1.0)],
 [(3, 1.0), (4, 1.0), (7, 1.0)],
 [(9, 1.0)],
 [(9, 1.0), (10, 1.0)],
 [(9, 1.0), (10, 1.0), (11, 1.0)],
 [(5, 1.0), (10, 1.0), (11, 1.0), (12, 1.0)]]

In [8]:
import numpy as np

In [9]:
#Matrix initialization
b = np.zeros([corpus.num_docs,corpus.num_terms])

In [10]:
from gensim import sklearn_api
sk_tfidf = sklearn_api.tfidf.TfIdfTransformer()

In [17]:
a = sk_tfidf.fit_transform(corpus)


0.3333333333333333

In [12]:
a

[[(0, 0.5773502691896257), (1, 0.5773502691896257), (2, 0.5773502691896257)],
 [(1, 0.44424552527467476),
  (3, 0.44424552527467476),
  (4, 0.44424552527467476),
  (5, 0.44424552527467476),
  (6, 0.3244870206138555),
  (7, 0.3244870206138555)],
 [(0, 0.5710059809418182),
  (6, 0.4170757362022777),
  (7, 0.4170757362022777),
  (8, 0.5710059809418182)],
 [(2, 0.7487922356593828), (6, 0.5469348542288004), (8, 0.3743961178296914)],
 [(3, 0.6282580468670046), (4, 0.6282580468670046), (7, 0.45889394536615247)],
 [(9, 1.0)],
 [(9, 0.7071067811865475), (10, 0.7071067811865475)],
 [(9, 0.5080429008916749), (10, 0.5080429008916749), (11, 0.695546419520037)],
 [(5, 0.4628644263314176),
  (10, 0.3380866887867002),
  (11, 0.4628644263314176),
  (12, 0.6761733775734003)]]

In [20]:
for i in range(len(a)):
    for j in a[i]:
        b[i,j[0]] = j[1]
matrix_T = b

In [21]:
matrix_T

array([[ 0.57735027,  0.57735027,  0.57735027,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.44424553,  0.        ,  0.44424553,  0.44424553,
         0.44424553,  0.32448702,  0.32448702,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.57100598,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.41707574,  0.41707574,  0.57100598,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.74879224,  0.        ,  0.        ,
         0.        ,  0.54693485,  0.        ,  0.37439612,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.62825805,  0.62825805,
         0.        ,  0.        ,  0.45889395,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.      

In [24]:
import pandas as pd
esa = pd.DataFrame(matrix_T,index=[i for i in range(np.shape(matrix_T)[0])],columns=[dictionary.get(i) for i in range(np.shape(matrix_T)[1])])
esa


interface  computer     human  response      time    survey    system  \
0   0.577350  0.577350  0.577350  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.444246  0.000000  0.444246  0.444246  0.444246  0.324487   
2   0.571006  0.000000  0.000000  0.000000  0.000000  0.000000  0.417076   
3   0.000000  0.000000  0.748792  0.000000  0.000000  0.000000  0.546935   
4   0.000000  0.000000  0.000000  0.628258  0.628258  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.462864  0.000000   

       user       eps     trees     graph    minors  frequency  
0  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000  
1  0.324487  0.000000  0.000000  0.000000  0.000000   0.000000  
2  0.417076  0.571006  0.000000  0.000000  0.000000   0.000000  
3  0.000000  0.374396  0.000000  0.000000  0.000000   0.000000  
4  0.458894  0.000000  0.000000  0.000000  0.000000   0.000000  
5  0.000000  0.000000  1.000000  0.000000  0.000000   0.000000  
6  0.000000  0.000000  0.707107  0.707107  0.000000   0.000000  
7  0.000000  0.000000  0.508043  0.508043  0.695546   0.000000  
8  0.000000  0.000000  0.000000  0.338087  0.462864   0.676173

In [25]:
esa.transpose().loc['trees'].as_matrix() + esa.transpose().loc['trees'].as_matrix()

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        2.        ,  1.41421356,  1.0160858 ,  0.        ])

In [31]:
test_1 = "survey trees graph"
test_2 = "human system"
test_3 = "minors"

test =[ "survey trees graph", "human system","minors"]

def get_word_rank(string):
    words = string.split()
    vector = esa.transpose().loc[words[0]].as_matrix()
    for i in range(1,len(words)):
        vector = vector + esa.transpose().loc[words[i]].as_matrix()
    return vector
def get_similarity(t1,t2):
    doc1 = get_word_rank(t1)
    doc2 = get_word_rank(t2)
    sim = np.dot(doc1,doc2)/np.sqrt((np.dot(doc1,doc1)*np.dot(doc2,doc2)))
    return sim


for i in test:
    for j in test:
        print "doc1:",i
        print "doc2:", j
        print get_similarity(i,j)
        print
    


doc1: survey trees graph
doc2: survey trees graph
1.0

doc1: survey trees graph
doc2: human system
0.043145850026

doc1: survey trees graph
doc2: minors
0.584311660826

doc1: human system
doc2: survey trees graph
0.043145850026

doc1: human system
doc2: human system
1.0

doc1: human system
doc2: minors
0.0

doc1: minors
doc2: survey trees graph
0.584311660826

doc1: minors
doc2: human system
0.0

doc1: minors
doc2: minors
1.0



In [32]:

In [32]:
from gensim.corpora.wikicorpus import WikiCorpus

In [33]:
wiki= WikiCorpus("enwiki-20170820-pages-articles.xml.bz2")

Process InputQueue-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/shubham/venv/local/lib/python2.7/site-packages/gensim/utils.py", line 858, in run
    self.q.put(wrapped_chunk.pop(), block=True)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 101, in put
    if not self._sem.acquire(block, timeout):
KeyboardInterrupt


In [34]:
data = sk_tfidf.fit_transform(corpus)

